/**
 * Uitleg per veld van het woningprofiel, getoond als hover/tooltip (ⓘ) in het
 * formulier. Beschrijft wat er ingevuld moet worden, een voorbeeld, en hoe de
 * waarde in de teksten wordt gebruikt. Sleutels gelijk aan FieldDef.key.
 */
export const FIELD_TIPS: Record<string, string> = {
  // Basisgegevens
  address: "Alleen de straatnaam, zonder huisnummer. Wordt gebruikt in de koppen (\"Wat je graag wilt weten over …\"), de websitetitel en de SEO-slug.",
  house_number: "Huisnummer zonder toevoeging, bijv. 120. De toevoeging vult u apart in.",
  addition: "Toevoeging bij het huisnummer, bijv. A, bis of 2-hoog. Leeg laten als er geen toevoeging is.",
  postcode: "Postcode in de vorm 1234 AB. Komt niet in de teksten, maar helpt bij controle en vindbaarheid.",
  city: "Plaatsnaam zoals die in de advertentie moet staan, bijv. Den Haag. Gebruikt in titels, SEO en lokale hashtags.",
  neighbourhood: "Wijk of buurt, bijv. Statenkwartier. Wordt gebruikt voor de locatiebeschrijving, SEO en hashtags (#Statenkwartier).",
  property_type: "Woningtype zoals u het wilt communiceren, bijv. herenhuis, bovenwoning of appartement. Bepaalt mede de toon en de websitetitel.",
  listing_status: "Huidige verkoopstatus. Bij 'in voorbereiding' kunt u al teksten maken; de status komt niet in de tekst zelf.",
  asking_price: "Vraagprijs in hele euro's, zonder punten (bijv. 1250000). Op social media alleen genoemd als 'Prijs vermelden op social media' aan staat.",
  sale_condition: "Kosten koper (k.k.) of vrij op naam (v.o.n.). Wordt bij de prijs vermeld.",
  living_area: "Gebruiksoppervlakte wonen in m² volgens de meetinstructie (NEN 2580). Alleen het getal, bijv. 142.",
  plot_area: "Perceeloppervlakte in m², alleen bij grondgebonden woningen. Leeg laten bij een appartement.",
  year_built: "Bouwjaar van de woning (vier cijfers). Wordt letterlijk genoemd; vul alleen een bevestigd jaartal in.",
  energy_label: "Energielabel volgens het geldige certificaat (A++++ t/m G). Wordt genoemd in de kenmerken.",
  rooms: "Totaal aantal kamers inclusief woonkamer en slaapkamers (zoals op Funda), exclusief keuken, badkamer en berging.",
  bedrooms: "Aantal slaapkamers. Belangrijk voor doelgroep en indeling.",
  bathrooms: "Aantal badkamers (ruimtes met douche of bad).",
  toilets: "Totaal aantal toiletten, inclusief toiletten in badkamers.",
  floors: "Aantal woonlagen, exclusief kelder en zolder als die niet bewoonbaar zijn.",
  floor_position: "Voor appartementen: op welke verdieping de woning ligt, bijv. 2e verdieping of begane grond.",

  // Woningkenmerken
  "kenmerken.woonkamer": "Afmetingen, ligging, lichtinval en bijzonderheden van de woonkamer, bijv. 'en-suite, 45 m², erker aan de straatzijde, openslaande deuren naar de tuin'.",
  "kenmerken.keuken": "Type en opstelling van de keuken, bouwjaar of renovatie, bijv. 'woonkeuken in L-opstelling uit 2021 met kookeiland'.",
  "kenmerken.keukenapparatuur": "Aanwezige inbouwapparatuur en merken als die relevant zijn, bijv. inductiekookplaat, combi-oven, Quooker.",
  "kenmerken.slaapkamers": "Per slaapkamer kort de grootte en bijzonderheden, bijv. 'master bedroom met inloopkast aan de tuinzijde'.",
  "kenmerken.badkamers": "Inrichting en jaartal van de badkamer(s), bijv. 'inloopdouche, ligbad, dubbele wastafel, vernieuwd in 2019'.",
  "kenmerken.buitenruimte": "Tuin, balkon of dakterras met afmetingen, bijv. 'diepe achtertuin van 15 m met achterom'.",
  "kenmerken.ligging_buitenruimte": "Op welke windrichting de buitenruimte ligt (bijv. zuidwest). Wordt vaak als verkoopargument gebruikt.",
  "kenmerken.uitzicht": "Wat u vanuit de woning ziet, bijv. vrij uitzicht over het park. Alleen noemen als het klopt.",
  "kenmerken.bergruimte": "Berging, kelder, zolder of vliering, met afmetingen waar bekend.",
  "kenmerken.parkeren": "Parkeermogelijkheden, bijv. eigen parkeerplaats, garagebox, vergunningparkeren. Noem kosten of wachtlijsten alleen als ze bevestigd zijn.",
  "kenmerken.lift": "Is er een lift in het gebouw of de woning?",
  "kenmerken.toegankelijkheid": "Bijzonderheden voor toegankelijkheid, bijv. gelijkvloers wonen, drempelloos, slaapkamer op de begane grond.",
  "kenmerken.authentieke_details": "Karakteristieke elementen, bijv. glas-in-lood, ornamentplafonds, originele schouw, paneeldeuren.",
  "kenmerken.renovaties": "Recente renovaties met jaartal, bijv. 'dak vernieuwd 2020, nieuwe kozijnen 2022'.",
  "kenmerken.onderhoud": "Algemene onderhoudsstaat, binnen en buiten. Feitelijk houden; gebreken horen bij 'Bekende gebreken'.",
  "kenmerken.beglazing": "Type beglazing, bijv. volledig HR++ of deels enkel glas.",
  "kenmerken.isolatie": "Aanwezige isolatie, bijv. dak-, vloer- en spouwmuurisolatie.",
  "kenmerken.verwarming": "Verwarmingssysteem, bijv. cv-ketel (bouwjaar), warmtepomp, vloerverwarming.",
  "kenmerken.zonnepanelen": "Aantal zonnepanelen of vermogen en of ze eigendom zijn of geleased.",
  "kenmerken.indeling": "Beschrijving per verdieping in looprichting (begane grond, eerste verdieping, …). Dit is de basis voor de sectie 'Indeling' in de Funda-tekst.",

  // Locatie
  "locatie.karakter_wijk": "Sfeer en karakter van de buurt, bijv. 'rustige, groene woonstraat met veel jonge gezinnen'.",
  "locatie.winkels": "Winkels in de buurt met naam of straat waar relevant, bijv. de Frederik Hendriklaan.",
  "locatie.horeca": "Restaurants, cafés en terrassen in de omgeving.",
  "locatie.scholen": "Scholen in de buurt (basis- en voortgezet onderwijs). Alleen noemen wat u kunt bevestigen.",
  "locatie.kinderopvang": "Kinderopvang en peuterspeelzalen in de buurt.",
  "locatie.speelplekken": "Speeltuinen en speelplekken in de directe omgeving.",
  "locatie.parken": "Parken en groen in de buurt, bijv. Westbroekpark op loopafstand.",
  "locatie.strand_duinen": "Nabijheid van strand en duinen. Afstanden alleen als ze kloppen.",
  "locatie.sport": "Sportverenigingen, sportscholen en sportvelden in de buurt.",
  "locatie.openbaar_vervoer": "Haltes en lijnen in de buurt, bijv. tramlijn 17 op 3 minuten lopen.",
  "locatie.bereikbaarheid": "Bereikbaarheid met de auto en uitvalswegen, bijv. snel op de A4/A12.",
  "locatie.overig": "Overige relevante bijzonderheden van de locatie die nergens anders passen.",
  "locatie.reistijden": "Alleen gecontroleerde reistijden, bijv. '10 min fietsen naar Den Haag Centraal'. Claude noemt nooit reistijden die hier niet staan.",

  // Juridisch en technisch
  "juridisch.eigendom": "Eigen grond of erfpacht. Bij erfpacht ook canon en voorwaarden invullen.",
  "juridisch.erfpacht_canon": "Jaarlijkse canon in euro's en of die is afgekocht, bijv. 'eeuwigdurend afgekocht'.",
  "juridisch.erfpacht_voorwaarden": "Algemene bepalingen en looptijd van de erfpacht, zoals vermeld in de akte.",
  "juridisch.vve_status": "Of er een actieve VvE is, met MJOP en reservefonds waar bekend.",
  "juridisch.vve_bijdrage": "Maandelijkse servicekosten/VvE-bijdrage in euro's.",
  "juridisch.vve_bijzonderheden": "Bijzonderheden van de VvE, bijv. geplande groot onderhoud of splitsingsakte-bepalingen.",
  "juridisch.monument": "Rijks- of gemeentelijk monument? Beïnvloedt verbouwingsmogelijkheden en wordt feitelijk vermeld.",
  "juridisch.beschermd_stadsgezicht": "Ligt de woning in beschermd stadsgezicht?",
  "juridisch.kadastraal": "Kadastrale aanduiding (gemeente, sectie, perceelnummer) en eigendomssituatie. Komt in de sectie 'Kadastrale informatie'.",
  "juridisch.technische_installatie": "Technische installaties en hun leeftijd, bijv. cv-ketel 2018, mechanische ventilatie.",
  "juridisch.bekende_gebreken": "Bekende gebreken uit vragenlijst of bouwkundig rapport. Wordt NIET in marketingteksten genoemd, maar voorkomt dat Claude onjuiste claims doet.",
  "juridisch.verkoopclausules": "Clausules die in de koopovereenkomst komen, bijv. ouderdoms-, asbest- of niet-zelfbewoningsclausule. De bijbehorende standaardpassage wordt dan letterlijk toegevoegd.",
  "juridisch.verkoopvoorwaarden": "Bijzondere verkoopvoorwaarden. Alleen voor interne controle; niet voor marketingteksten.",
  "juridisch.oplevering": "Opleverdatum of -afspraak, bijv. 'in overleg' of 'per 1 maart'. Wordt letterlijk overgenomen in de sectie 'Oplevering'.",

  // Positionering
  "positionering.usp_1": "Het sterkste verkoopargument, bijv. 'zonnige tuin op het zuiden'. Dit krijgt de meeste nadruk in de introductie.",
  "positionering.usp_2": "Tweede verkoopargument. Moet feitelijk door het profiel worden onderbouwd.",
  "positionering.usp_3": "Derde verkoopargument.",
  "positionering.onderscheidend": "Wat deze woning anders maakt dan vergelijkbare woningen in de buurt. Helpt Claude een onderscheidende opening te schrijven.",
  "positionering.doelgroep": "Voor wie is deze woning bedoeld, bijv. jong gezin, expats of senioren. Bepaalt perspectief en toon.",
  "positionering.uitstraling": "Gewenste uitstraling van de tekst, bijv. 'chic en ingetogen' of 'speels en familiair'.",
  "positionering.verhaal": "Achtergrond of geschiedenis van de woning die het vermelden waard is, bijv. het oorspronkelijke ontwerp of de architect.",
  "positionering.instructies": "Extra aanwijzingen voor de tekst, bijv. 'benadruk de rustige ligging'. Feiten, privacyregels en de schrijfwijzer gaan altijd voor.",
  "positionering.niet_noemen": "Onderwerpen die nergens in de teksten mogen komen, één per regel (bijv. 'scheiding verkopers', 'bouwplannen achterburen'). De eindcontrole controleert hierop.",

  // Publicatie
  "publicatie.funda_url": "Link naar de Funda-advertentie zodra die online staat. Wordt niet in de tekst zelf gebruikt.",
  "publicatie.website_url": "Link naar de woningpagina op de eigen website.",
  "publicatie.bezichtiging_url": "Link waarmee geïnteresseerden een bezichtiging kunnen aanvragen. Kan in social-mediaposts worden gebruikt.",
  "publicatie.omgevingsfilm_url": "Link naar een video of omgevingsfilm van de woning.",
  "publicatie.contactpersoon": "Naam van de makelaar die het contactpunt is voor deze woning.",
  "publicatie.telefoon": "Telefoonnummer van kantoor of makelaar. Gaat NIET naar Claude; mag wel in teksten staan als u het zelf toevoegt.",
  "publicatie.email": "E-mailadres van kantoor of makelaar. Gaat NIET naar Claude; mag wel in teksten staan als u het zelf toevoegt.",
  "publicatie.prijs_op_social": "Aanzetten als de vraagprijs in Facebook- en Instagramteksten genoemd mag worden. Standaard uit.",
  "publicatie.publicatiedatum": "Geplande publicatiedatum. Alleen voor planning; komt niet in de tekst.",
  "publicatie.extra_hashtags": "Eigen hashtags die altijd mee moeten, zonder #, gescheiden door spaties of komma's, bijv. Statenkwartier herenhuis.",
};
